### ISSUE TITLE
Resource Editor: Simple Linking Properties MVP

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#103]
(use #92 wherever it helps)

Links are external resources like #72 but some links are simpler than others.

This is for simple label+link properties, they are inline properties in RHS resource editors.

(in #72 we _may_ have external services as Resource Editors in their own right)

https://www.sketch.com/s/d40c5942-ae96-4fad-a0bf-6fe7f8e3cf1e/a/ZOoQmVv

**Comment by stephenwf** [comment]
![image](https://user-images.githubusercontent.com/8266711/185628486-01cd6966-9ce1-4c1a-aa91-8d4e66c11a27.png)
