### ISSUE TITLE
Identify possible components

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#107]
This is a placeholder task to make sure we have other tasks (and storybook tags) in place for all the UI components we need.

---

**First mentioned**, _reused_

**Thumbnail** (not sure if actually a component as such...)
**Canvas strip** #102
**Canvas grid** #70, #71
**Canvas grid contextual menus** #71
**Canvas surface** #98 (and see #17 and https://github.com/digirati-co-uk/iiif-manifest-editor/discussions/29)

**Tabs** (for RHS panel) #108

**Resource Editor Panel**
-> _Tabs_
 
**Single Language Map property editor** #67
**Label/Value Language Map property editor** #67
-> 2 x _Single Language Map property editor_

Metadata property editor #68
-> List of _Label/Value Language Map property editor_

**Single free string property editor** #73
**String List property editor** #73
**Short list property editor** #109 (e.g., if different for viewingDirection)
**Date property editor**  #110 (not a date picker though)

**Canvas selector** #112 (for picking a canvas, e.g., for start property)
(this may be a dropdown or may be a condensed horizontal strip)

(all of the following can appear as list members; always "add another")

**Dimensions** (w,h,duration) #113
used for canvases (where the w,h are dimensionless)
and for media (where the w,h are pixels)
Usually filled by URL-analyser but can be free-edited (especially canvas)

**IIIF Browser** #111 (collections -> Manifests -> Canvases) - for selection of canvas
(possibly uses _Canvas selector_ at the last stage)?

**New Canvas modal**
-> _Thumbnail_
-> _Dimensions_
-> _IIIF Browser_

In the following _mini_ represents the stand-in for an element that is edited in full in a further panel or modal.
As above these can all be lists

**Media resource mini** #94
**Media resource full** #94

**External resource mini** #72
**External resource full** #72

**Service mini** #114
**Service full** #114 (how similar is this to external resource? Not always external but always a service) 

**Canvas target** #115 picker/display

**Choice editor** (later)

**Painting annotation editor** #96
 - Body: (_Media Resource_) or (_Choice editor_) or (..later)
 - Target: (_Canvas target_)

**Canvas media editor** #97

**Agent editor** #85

Non-painting annos

**TextualBodyEditor** #117

**Annotation page pager** #100
**Annotation mini** #118
**Annotation full editor** #99
->label etc are property editors already defined
->Body
... ->_TextualBodyEditor_
... ->_External resource mini_
... -> _Single free string property editor_ (body is a raw URI - otherwise it's probably an external resource)
-> Target: (_Canvas target_)

**Comment by stephenwf** [comment]
Closing, list may be out of date.
