### ISSUE TITLE
Capture models define what's editable

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#11]
(NB this might not be exactly the same as capture models in Madoc)

The user of the manifest editor is able to focus on different resources within the manifest. A canvas, a range, the manifest itself...

What is editable - i.e., what UI the manifest editor shows for the current scope - is defined by a capture model.

An out of the box manifest editor has a set of capture models, one for each possible scope, that allows the user to edit/create IIIF properties and resources in line with the spec, and nothing more.

Sometimes, a deployment of the manifest editor will wish to simplify the interface - to not expose all possible editable things.
Sometimes, a deployment of the manifest editor will wish to extend the interface - add custom behavours, additional custom properties, or specialised editors for defining an external resource.

In both cases, the manifest editor has been configured with a non-default set of capture models. The manifest editor uses the capture model configuration to generate the editing UI for the scope of the user's current focus.

**Comment by jpadfield** [comment]
Would a toggle option be possible to go from simple - to complex etc - model 1, 2, 3 .... n ?

Another thought - would this process allow for default values in the defined models? 

I want the author to always be me, I want the rights to always be CC0, My manifests are all supported by Grant number 1, etc ....

**Comment by tomcrane** [comment]
I think this could be done via templates. As well as supporting sources like the IIIF Cookbook for starting points for Manifests, rather than a blank slate, you can via config add in additional ones - such as a Manifest with `provider` and other metadata pre-filled.

This also sounds like something that would be useful for per-user config, stored in local storage.
As well as pre-canned templates under **File->New**, I also get any personal ones I've added.

**Comment by stephenwf** [comment]
Although not using capture models yet, the process for defining "Creators" for different types of resources has been implemented.
https://github.com/digirati-co-uk/iiif-manifest-editor/tree/feature/editor-changes/manifest-editor/src/_creators

We have templates for starting points (Manifests) which can be expanded.

There is also an "Overview" panel in the editing side that shows non-empty values together. We don't currently have a way to specify global "Read-only" for a property, but this will be required soon anyway for locking resources that are being edited elsewhere.
