### ISSUE TITLE
Date editor

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#110]
For navDate - probably NOT a date picker because of the historical nature of the dates.

(duplicated note)

`navDate` is a plain literal XSD date string. We can just have a string field with a validator. A date picker would probably be less useful because the dates could be years (or hundreds of years) ago.

Possible:

![image](https://user-images.githubusercontent.com/1443575/158851570-8eac0f45-07ae-43af-b09a-20e1c13d4dd2.png)

**Comment by stephenwf** [comment]
The above is modelled on:
```
<input type="date" />
```
and
```
<input type="time" />
```

**Comment by stephenwf** [comment]
Additionally in the code the property editor has guards to ensure the value remains valid: https://github.com/digirati-co-uk/iiif-manifest-editor/blob/1837b8408f58bec294b801196487614bb3985640/manifest-editor/src/editor-api/NavDateEditor.ts
