### ISSUE TITLE
Canvas Selector

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#112]
For picking a canvas, e.g., for the `start` property

![image](https://user-images.githubusercontent.com/1443575/158852541-96cde024-785d-4764-9b39-effe5367dca9.png)

This might be used in #111 - (this may be a dropdown or may be a condensed horizontal strip)

**Comment by stephenwf** [comment]
A note here, Madoc wraps this dropdown library:
https://github.com/based-ghost/react-functional-select
https://based-ghost.github.io/react-functional-select/?path=/story/react-functional-select--single-select

Which can offer some autocomplete - and even a thumbnail/icon
https://based-ghost.github.io/react-functional-select/?path=/story/react-functional-select--advanced

**Comment by sarahos** [comment]
Show the start canvas and navigate to it as first pass 

Should appear in Structural tab

**Comment by stephenwf** [comment]
Start now uses the IIIF Browser, so you can scroll through and choose a start canvas. Appears in the linking tab, for parity with the specification.
