### ISSUE TITLE
TextualBodyEditor

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#117]
This is one of our (eventually several) annotation body editors... or maybe they are capture models...

![image](https://user-images.githubusercontent.com/1443575/158875424-7b3127b9-1d11-4638-b317-2986eb6a0362.png)

**Comment by stephenwf** [comment]
The creation process uses a single multi-lingual field and the editing process uses a list of editors (as at this point they are multiple content resources). Room for improvement, and also limitation that you cannot add extra languages after initial creation - this requires deletion and recreation of the annotation. However closing as it's MVP.
