### ISSUE TITLE
Editing metadata and other multilingual properties

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#13]
The manifest editor should allow editing of label and description on any resource that supports them.
It should allow a metadata block to be added and populated on any resource that supports it.

These properties/resource use the same language map editing widget throughout.

(specialisation of #8)

**Comment by jpadfield** [comment]
Will this also cover the options for users to add in new bespoke metadata to the various sections of a collections or a manifest? The options for applying "keywords" or "categories" but more specific things like dates or locations (which might already be covered my the maps work) could be very useful.

**Comment by tomcrane** [comment]
Yes, this will allow arbitrary new entries to be made in the manifest `metadata` block. In multiple languages, too, if needed.

**Comment by stephenwf** [comment]
All fields that require a language map are now editable on all resources with the base Manifest editor configuration. The source of the languages will come from #64 

Supports multiple languages, multiple values per language and IIIF-compliant HTML values in a visual WYSIWYG or non-compliant HTML in a raw-text editor.

![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/016c42c0-fd47-4d4b-8d57-9e5423ddefc1)
