### ISSUE TITLE
"Splash Screen" changes

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#135]
- [x] Add a prominent **Open Manifest** call to action. So the default view is Open Manifest, New Manifest, Recent Manifests and each of them are the same kind of size. The first one obviously only needs one box, with something "open-y" - a curving arrow?
- [x] Do we need the "Oops" view? Can't that just be the default view above? - yes
- [x] Remove the copy, and put it in a modal that is opened from Help -> About.

**Comment by tomcrane** [comment]
Simplify to list of options - a larger version of the File menu.

Open
New
Recent

@diegolago to mock up.

**Comment by stephenwf** [comment]
I think some visual tidy should be improved here

- [ ] Max width on the getting started section
- [ ] Switch to list for recently opened resources
