### ISSUE TITLE
Browse and select from existing published IIIF resources

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#20]
- In building my new manifest, I'd like to include images, audio and video from other, existing IIIF
 - (For example, I'm putting together a sequence of views of a painting for a manifest that will accompany an article)
 - This other IIIF might be published by my institution, or it could be anyone's public IIIF
 - I need to browse through other IIIF Collections and Manifests without disrupting the Manifest I'm working on right now

**Comment by tomcrane** [comment]
UI issues
 - differentiating between including a _Canvas_ from another Manifest and including a content resource (e.g., an image) from another Manifest.
 - For much published IIIF this won't appear to be a meaningful distinction on the surface - unlike, say, copying a PowerPoint slide from one presentation to another where it's clearer that the slide and all its content comes along in one go.
 - Most common scenario where this becomes significant - the Canvas has OCR text and annotations along with the image, so copying the Canvas brings these with it whereas copying the image will not.

**Comment by jpadfield** [comment]
It could be good to have an option to copy canvas or copy image - for the instances when one did not want the annotations.

When copying canvases that referenced annotations from an external service, the system would need to be able to (have an option for) pull in the annotations and hard-wire then into the manifest rather than just copying the reference used in the original - thus allowing local editing if required.

**Comment by stephenwf** [comment]
That's an important point, when you "copy" a canvas, are you always copying just the canvas or everything associated with the canvas (ranges, annotations). UX would need to strike a balance between being intuitive and simple, while also having enough control over these types of things.

**Comment by jpadfield** [comment]
- Copy just the image
- Copy image and annotation references
- Copy image and create local copy of annotations to allow editing
- Copy image and annotation references - and allow additional new local annotations ?

**Comment by tomcrane** [comment]
Addressed by #111
