### ISSUE TITLE
Textual context associated with painting annotations

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#208]
This is a placeholder issue to support Delft's use cases. Currently their model requires `label` and `summary` on painting annotations. This model may change (https://github.com/digirati-co-uk/delft-static-site-generator/issues/142) but regardless of how it ends up we need to make sure that the ME has the UI to capture the data Delft needs.

**Comment by stephenwf** [comment]
![image](https://user-images.githubusercontent.com/8266711/205016453-e336cfc5-e776-4dfc-b585-6a1c1f9f2afa.png)

On painting annotations there is a new "Descriptive" section collapsed if there are no values. If you open it up, you can add a Label and a Summary.

![image](https://user-images.githubusercontent.com/8266711/205016681-a43cd80d-890a-4670-a9e1-aa96cf802765.png)
