### ISSUE TITLE
Create and edit version 3 Manifest 

### ISSUE THREAD

**Issue by glenrobson** [digirati-co-uk/iiif-manifest-editor#23]
Hopefully already possible but this is our main reason for possible switching to a new editor. We mainly work with images but supporting AV would be an extra bonus.

**Comment by tomcrane** [comment]
The manifest editor will be able to load 2 and save as 3, and vice versa.
It will default to 3 for new content.

It will support some form of AV, hopefully addressing the most common simple use cases.
