### ISSUE TITLE
Allow image positioning for layers 

### ISSUE THREAD

**Issue by glenrobson** [digirati-co-uk/iiif-manifest-editor#25]
Not top priority for us but in the training we get a number of people who want to register two IIIF images into the same canvas and there aren't great tools available to do this.

**Comment by jpadfield** [comment]
Is the functionality to just add layers without further positioning already included?
I agree the positioning thing would be good but perhaps not top priority but the ability to simply layer images would be a lot higher ...

**Comment by jpadfield** [comment]
This one also speaks to the ability to do relative size - which though not a need is mentioned in our project: https://canvas-panel.digirati.com/developer-stories/rightsize.html

**Comment by stephenwf** [comment]
This is now implemented.

If you start with an empty canvas, a size will be selected automatically (like 1024x1024).

If you then add a first image to that canvas, the canvas height/width will match the image or image service dimensions.

When you add a second image, it will be scaled down and placed in the middle of the canvas.
![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/ffe1f1a0-e087-49ba-a13d-81e011f66ca5)


You can then use the handles to resize (preserving the aspect ratio automatically) and drag it around the canvas. Holding spacebar will allow you to move and zoom the image to as you reposition. 

The first canvas can be switched from "target whole canvas" to target a box:
![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/a5787a37-80fa-457b-9f22-372b3f55febf)

and after:
![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/774877f3-b2b4-4d93-aa92-414cfb9f522e)

where the image is scaled down to the middle of the viewport:
![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/409c648f-835b-4507-8575-9d7cf123519b)

it can also be rescaled. The canvas dimensions can also be changed after adding the first image. This was done to strike a balance between ease of use and flexibility. It's not currently possible to create an empty canvas - make it a certain size and then start adding content, you must first add content and then choose your canvas size.
