### ISSUE TITLE
Simple annotation requirements

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#27]
In addition to creating manifests and collections the editor allows:

Creating an **_inline_** annotation page for any canvas, that can contain annotations with:

* motivations chosen from `highlighting`, `linking`, `commenting` (more...)
* Textual bodies
* Bodies for linking to other resources
* Bodies that tag other resources
* Targets that are points (spatial or temporal or both)
* Targets that are boxes (xywh)
* Targets that are time durations

We'll leave more complex targets for a future phase (svg).

For making a Balenciaga-style narrative, you might want a single anno page attached to the manifest itself with annos targeting multiple canvases - so that this single JSON block is "playable" by a slideshow type display.

https://www.vam.ac.uk/articles/gilbert-mosaics

Or an Ocean Liners style guided tour but over two canvases not one... 

This feature allows the manifest editor to continue to be used for making slideshows, guided tours and other exhibits.
However it's still a manifest editor, not a standalone AnnotationPage editor. Is that right?

**Comment by jpadfield** [comment]
Curious about your last sentence.

Are you saying that the annotation bit is integrated into the system rather than a standalone tool

or are you implying that a standalone AnnotationPage editor might have additional functionality that this would not?

**Comment by tomcrane** [comment]
I can imagine some all-signing all-dancing annotation workbench that allowed you to make all sorts of complex annotations on IIIF material. We even have something like that in Madoc.

At the other end of the scale there's a pure Manifest creator - assemble a sequence of canvases, add images and AV to canvases, but you can't make other kinds of annotation, you can't draw a box for a tag. The Bodleian editor, for example, is not an annotation tool.

In its v1 guise, the Digirati Manifest Editor allowed you to create annotations, for the purposes of building narratives (like Ocean Liners).

The question is... how far does it go? It shouldn't try to be the all-singing all-dancing annotation workbench, but it should offer some simple annotation functionality to be a useful tool for assembling slideshows and exhibits like Delft's.

We need to decide where the line gets drawn.

**Comment by tomcrane** [comment]
I _think_ so.

**Comment by jpadfield** [comment]
Longer term - I am curious about the potential of adding metadata to annotations .... tags are possible but could you have author, data, multiple descriptions of different types, etc ??

**Comment by tomcrane** [comment]
An IIIF annotation could be anything supported by the [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/) - the question for us is how much UI do we develop to capture the possibilities?

By making the annotation capture UI modular and extensible, we can provide for common scenarios out of the box, but give people ways of extending the editor to support their more complex use cases and annotation requirements.

**Comment by tomcrane** [comment]
Additional note - the above comment suggests a manifest-level annotation list as a way of making Balenciaga-style narratives, where some slide transitions are moving the image attention point to a different part of the same image.

After writing #36 I changed my mind about how to model this. The Manifest implied in that issue has multiple canvases with the same image on them instead. This produces a better experience in the non-specialist viewer, especially if that viewer also understands the highlighting annotation. And it's just a bit more JSON!

The specialist viewer knows that if the next canvas has the same `painting` annotation, then it should animate the transition to a different highlight area.

**Comment by stephenwf** [comment]
We have 2 patterns for adding annotations:

- Create, view, delete
- Create, view, edit

The two components of an annotation: `target`, `body` are handled separately. First a target is set, then a body is chosen. For other properties permitted by IIIF (label, summary etc.) these are editable for all annotations.

Some bodies and targets can be edited, some can only be viewed (so you have to delete and re-add to change).

Supported annotation bodies (painting and non)

- HTML body annotation (multi-lingual)
- YouTube annotation
- Image Service annotation
- IIIF Browser (extracting painting annotations, or just image services)
- HTML describing annotation
- Annotation without body

Targets:
- Full canvas
- Box selector

Generic property editing:
- label
- summary
- thumbnail
- rights
- required statement
- metadata pairs
- behavior
- motivation
- timemode
