### ISSUE TITLE
Editable resources - loading and saving

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#4]
Load a Manifest
Create a new Manifest
Save a Manifest

Load a Collection
Create a new Collection
Save a Collection

See [Loading ](https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Loading-IIIF-for-Editing) and [Saving](https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Saving-IIIF) in the Wiki for a more detailed explanation

**Comment by tomcrane** [comment]
First version of this demonstrates the persistence: #26 

Then the UI is iterated to become a visual tool.

**Comment by jpadfield** [comment]
Perhaps obvious :-) - but also

Load Manifest(s)/Collection(s)
Combine Manifests/Collections to create new Manifest/Collection
Save Manifest/Collection

**Comment by stephenwf** [comment]
Opening of both Manifests and Collections now supported. Persisted in localstorage (or eqv.) and able to be exported as Presentation 3.
