### ISSUE TITLE
MVP Configuration System

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#48]
Manifest Editor has a concept of the loaded configuration.

 - [x] can be set in code (probably most common)
 - [ ] can be set/overriden on the query string of the containing page
 - [ ] will load a named configuration file `<param>-configuration.json`
 
Initially, for MVP, we will just throw whatever config we need to get things working in here.  E.g., the preview config.

But in the refined version #64 , we consider more details of how config works.

## Acceptance

 - [x] configuration for the Preview menu comes from a separate configuration.json file that is part of the build.

**Comment by stephenwf** [comment]
Related to App/Widget configuration: https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Extending-Manifest-Editor
