### ISSUE TITLE
Browseable resources

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#5]
(these are resources you might open while editing resources in #4) - you are not editing these resources, you are browsing them to pull canvases or perhaps individual content resources from them)

 - Collections (hierarchically)
 - Manifests
 
See [Import of IIIF Resources](https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Import-of-IIIF-Resources) and [Import of Content Resources](https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Import-of-Content-Resources) in the Wiki.

**Comment by tomcrane** [comment]
If search results for IIIF are delivered as a Collection, or possibly as a content state, then these also fall under "resources you might open while editing resources"

e.g., if some other system offers exportable search results (or a link-to-json) as IIIF collections or content state anno lists, the manifest editor can load them for further selection.

**Comment by tomcrane** [comment]
This "IIIF world browser" should be a standalone component that is used in Manifest Editor, but can also be used in other applications such as a CMS or online publication.

It uses Canvas Panel itself, but also is seen in other applications made from Canvas Panel.

In Manifest editor you would use it in two ways:

 - browsing collections -> manifest -> canvas to select a canvas to **bring in**
 - When creating linking annotations in a canvas _to another IIIF resource_, you would define your anno area (draw box or shape) (probably on Canvas Panel), then use this tool to browse IIIF - but you wouldn't stop at Canvas selection, you'd be able to _draw a box in the target canvas_.

**Comment by tomcrane** [comment]
See https://github.com/digirati-co-uk/iiif-canvas-panel/issues/90

**Comment by tomcrane** [comment]
Other browse scenarios:

If you're adding a new Canvas from a known existing image service endpoint, that's OK.
If you're adding a new Canvas by browsing existing IIIF Collections and Manifests, that's also OK.

There's an intermediate scenario, where, by whatever means, you have a list of image service endpoints - but they are not wrapped in any IIIF Presentation API resource. That's what you came to the Manifest Editor to do!

So as well as "Open" understanding Manifests and Collections, if it encounters something else it should *try to coerce it into a list of one or more image services* and present them in the UI as thumbnails you can drag into your manifest, just as if they were in a Manifest.

It could make something out of plain text lists, CSVs, or sensible JSON arrays.

**Comment by stephenwf** [comment]
IIIF Browser now available when adding media to a canvas, or when adding a new canvas to choose from an existing Manifest. Supports browsing both manifest and collections. Additionally it will save recent items in local storage (in the form of a local IIIF collection).

![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/fa94167b-387a-4fa8-baf0-699f7608809d)
