### ISSUE TITLE
New/Add Canvas dialogue

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#52]
Assuming this is a modal dialogue for now. I'll use the term "dialogue" for the UI that carries this function.

**This dialogue has to support the scenario of adding a new, empty Canvas**. In PowerPoint or Google Slides, this feels natural because a new slide already has dimensions - and with a slide, the most likely thing we're going to do with it is start typing on it, or perhaps place a picture on it, somewhere.

**However**, in ME, that flow of adding a new Canvas then adding content to it is, I think, *not right* for how people will use this *most of the time*. I think it will get annoying for people to have to follow that process, because most of the time you are adding _media_ (e.g., an image) to a sequence of media. Most Manifests are pages of books, or sequences of artworks, or whatever; not slides with text and pictures "on" them.

Only a tiny, tiny fraction of Canvases have multiple images on them. 

While it's true that ME will encourage more of the multiple-image kind of IIIF, it's still going to be rare to start with the canvas as a blank slate in the way you start with a PowerPoint slide as a blank slate. Because most of the time that would result in "make a canvas, put an image on it, _adjust the canvas dimensions to match the image_... repeat, repeat, repeat..."

So this dialogue needs to take media, and make the canvas from the media, by creating a canvas of the same dimensions. So users can think about the next image they want to add to the sequence, rather than think about the Canvas they need to make, of the right size, to put that image on, then put the image on it.

And more: unless you are in a context where you are very clearly adding more media to an existing (perhaps blank) canvas, this dialogue is the natural action for "I want to add more images to my Manifest" - any [+] button in the context of the manifest's thumbnail strip, thumbnail field, etc. **Adding new media is almost always going to involve automatic creation of a canvas for it to live on.**

But... we don't want to hide the nature of the Canvas from the user. So the design of this dialogue is very important.

The Canvas might also come from another existing piece of IIIF - I want my New Canvas in this manifest to be something from an existing Manifest.

MVP:
Note - see further design thoughts in comments below.

Most obvious call to action is a prompt for media:

----------------------------------

URL of Media [_____________]  [ ⟳ ]
_(Any image, IIIF Image Service, audio, video or IIIF Manifests and Canvases)_

Canvas dimensions:
width  [ _ ]  height [ _ ] | duration [ _ ]
_these will be filled automatically from content_

[ Add Canvas ] [ Cancel ]

---------------------------------

When the user pastes a URL into the text box, the ME could start analysing it with #45 

It will know what it is. Most of the time it will be able to fill the dimensions boxes automatically, but sometimes it will need to know a bit more about your intent. If you paste a Manifest URL in here, and that Manifest has more than one Canvas, it will show a thumbnail strip and ask you to pick which canvas. And if you do that, or have provided a plain Canvas URL, or a Manifest with one Canvas, or a Content State that evaluates to a single Canvas, it needs to ask you two more questions, via additional checkboxes:

 - [ ] Keep source Canvas ID
 - [ ] Keep source Canvas properties

Leaving both of these unchecked will result in a Canvas of the same dimensions, with the same `painting` annotations, but no other properties of the source. 

There's nothing stopping you changing the dimensions after they have been filled in for you.

There's also nothing stopping you failing to provide a URL - you _can_ create a blank canvas here. But if a URL didn't fill out the dimensions, you'll have to do it manually - you can't [OK] this dialogue without width+height, or duration, or both.

**Comment by tomcrane** [comment]
I _think_ that later configuration could add a tab to this dialog.

e.g., a DLCS tab.

**Comment by tomcrane** [comment]
Mock up of _some_ of this here:

https://tomcrane.github.io/scratch/me/new-canvas.html

**Comment by stephenwf** [comment]
We could simply the dialog slightly by moving the choice between a complex or simple canvas before the dialog (2 buttons? "+ add image", "+ add image on [complex ..?]")

**Comment by tomcrane** [comment]
When the URL is that of a Manifest and there is more than one canvas in the Manifest, something like this:

![image](https://user-images.githubusercontent.com/1443575/154988715-7fabcf7d-a71e-4dc8-a8c4-149283388451.png)

(from https://narrative-editor.netlify.app/)

...but maybe just a strip? We can experiment.

**Comment by tomcrane** [comment]
Proposal

![image](https://user-images.githubusercontent.com/1443575/159692391-78d4ce6d-7fce-4d1f-81e5-92452997b3d9.png)

Dimensions become visible if "empty canvas" checked

Dimensions are displayed by the URL analyser as information - 

"This image/service is 3434 x 3210. 
~The Manifest Editor will create a Canvas 3434 x 3210 from this image service~".

(second lang string might be blank in config therefore omitted).

**Comment by stephenwf** [comment]
For language string, if you had:
```js
t('This image/service is {width} x {height}', { width, height });
```
Then that single string could be translated (perhaps for training)
```json
{
  "This image/service is {width} x {height}": "This image/service is {width} x {height}, the Manifest Editor will create a Canvas {width} x {height} from this image/service"
}
```

**Comment by tomcrane** [comment]
I have updated this mockup to reflect the discussions above

https://tomcrane.github.io/scratch/me/new-canvas.html

One thing it does (by accident) is retain the dimensions if you start with media but then decide you want an empty canvas.
This is probably quite useful.
