### ISSUE TITLE
Preview UI and service integration for mechanism=previewService

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#54]
Requires #55

This is the initial implementation of https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Preview

- [x] Preview system with Mirador & Universal Viewer
- [x] Preview system with these choices configurable

With two links, one to UV and one to Mirador
We'll need to host our own Mirador to have a web page that can take a iiif-content or manifest parameter.

The config sets the two previews, and the UI defaults the first in the list to the button press (if you don't open the drop down).

The button then remembers this choice and says

> Preview ({label}) 

so you'll invoke the last-used preview service by pressing the button.

For this reason:

The button needs enough space to carry labels
Config should keep the label short!

The Manifest Editor should be aware of the TTL set by the preview and inform the user. When clicking the preview button or an option from the drop down, and the mechanism is `previewService`, the Manifest Editor:

* Pushes the current Manifest to the preview service
* If any errors, show message and abort
* Using a non-modal (?) alert (e.g., a bar) message the user that the link will expire in xxx hrs.
    * Include a "don't show again" in this bar.
* Once it has a response with a ttl, open a new window on the formatted template string, replacing {iiifResource} with the URL

Possible text:
-------------
A preview of this Manifest is now available at **{link here}** ⎘ (copy link)
This preview will expire in 48 hours.
For a permanent version, select Permalink from the Save As menu.

[X Close] [ ] don't show this message again in this session

------------

(close X probably in the top corner, etc) - this is a non modal alert like [bootstrap](https://getbootstrap.com/docs/4.0/components/alerts/#additional-content)

See https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Preview for the full mechanism

**Comment by diegolago** [comment]
- Preview the manifest with all viewers and it works nicely!
- I like the addition of the viewer name to Preview button as long as it only shows once a user selected one rather than list a default one. Was this something you wanted to add to the UI for users of just debugging for you?
- The preview button would need some breathing space (padding) but I will follow your lead on when to focus on snagging the UI. It might be better to work that in chunks rather than item by item
- For some reason, the URL copy doesn’t work for me. Tried on Chrome and Safari.

**Comment by tomcrane** [comment]
(for reference the fuller version of Preview thinking is here - https://github.com/digirati-co-uk/iiif-manifest-editor/wiki/Preview)

> Was this something you wanted to add to the UI for users of just debugging for you?

For all users, with the behaviour above - it remembers your selection and that becomes the default button action.

One thing to think about in future is whether a user can add a new target to the list (as a personal preference). They are assumed to be set up in config, but the casual user can't edit the config of the application on the server. But there could be a "Add new preview target" option somewhere which stores their personal preview targets in local storage.  Anyway one for later.
