### ISSUE TITLE
Make a Simple Top Bar

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#57]
This task begins to put some of the UI into components, even if the distinction between Shell and Apps is still being thought about.

## Acceptance criteria

![image](https://user-images.githubusercontent.com/1443575/153216571-d4596315-3207-4e81-8524-057861ee7ec7.png)

 - [x] The preview functionality is now on the right of this component
 - [x] The Heading is the `label` property of whatever is loaded into Vault (the main thing loaded into Vault)
 - [x] There is a File and a Help menu (we'll add more later)
 - [x] The File menu has **Open**, **Save**, **Save As...**, **Export**
 - [x] The Help Menu just as **About**
 - [x] All of those menu options just need to show they have been clicked (even just `alert(..)` !), if there's nothing to go there yet.

**Comment by tomcrane** [comment]
Requires #48 just to carry the preview config (and any other related bits of info)

**Comment by diegolago** [comment]
Look good to me. As I spoke with Kelsie, we need to define a general style for the ME. This should be a separate issue to this.
