### ISSUE TITLE
External Service and Resource Editor Component

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#72]
Many IIIF resources can have links to external services and resources.

While some of these may have specialised UI components of their own (e.g., an image service), there is a need for a general purpose UI component that can be used to set the values of fields that can take an array of external resources. For example, the properties `seeAlso`, `service`, `homepage`.

Common properties _of the external resource/service_:

- `id`
- `type`
- `label` (uses #67)
- `format`
- `language`
- `profile` (recommended for `service`)

## Acceptance

- [ ] When a Manifest or Canvas is selected as the current editable resource, all of its linking properties are displayed by the above widget
- [ ] For any array property, the user can add and remove resources to the list of resources for that property - including removing all members, and adding a member to an empty list.

## Notes

Future configuration can provide further refinement of behaviour. Such as, different help text or validation depending on which property the resource is being used on (e.g., `homepage` and `seeAlso` could have different help text for the `id` property editor).

**Comment by tomcrane** [comment]
There might be two forms of this component.

![image](https://user-images.githubusercontent.com/1443575/158869552-c8598973-27e0-4a6d-b533-3e1b0c43ff2c.png)

If the external resource is very simple it could be just a label and a URL and all inline - no "mini" version that launches the full version.

But when the external resource can take lots of fields (profile, language... lots more) then it would need to adopt the pattern of a reduced inline form so you can see it, that launches the full editor for an external resource.

HTML demo:

![image](https://user-images.githubusercontent.com/1443575/158869633-e2765048-7596-4623-a478-5fbc3ff66690.png)

leads to

![image](https://user-images.githubusercontent.com/1443575/158869687-bef349ea-641d-4964-b526-254d19e3e31b.png)

**Comment by tomcrane** [comment]
Further question - do we use the same component for services? There are some differences - see #114

**Comment by tomcrane** [comment]
The external linking properties need an MVP form of this widget, to fix the current behaviour:

![image](https://user-images.githubusercontent.com/1443575/175015241-1a4e9387-554a-4488-b3a5-3020ad35c012.png)

(see also #186)

They need to reflect the data, e.g., 

![image](https://user-images.githubusercontent.com/1443575/175015438-cedbf582-48d6-4d89-ba15-8a886872ae6a.png)

**Comment by stephenwf** [comment]
Linking properties appear in the editor:
![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/98d7226e-7e83-4fb7-983a-fd2ac2c8c84a)

And their generic properties are editable:
![image](https://github.com/digirati-co-uk/iiif-manifest-editor/assets/8266711/f7f5affb-797d-4d4f-b123-64dcea59816e)
