### ISSUE TITLE
Visual appearance pass-through

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#89]
Take the current implemented features and apply the design approach from Madoc to all the components.

Without adding new functionality features to the UI, make a pass-through to bring all _current_ implemented features up to a releasable design level.

This does not require an independent design system at this stage.

## Acceptance

 - [ ] @diegolago is happy for the application to be seen in public
 - [ ] We are all happy for this!

**Comment by ionab** [comment]
https://madoc-storybook.netlify.app/?path=/story/legacy-user-pages--login-page
Storybook


https://capture-models.netlify.app/?path=/story/input-types-all-types--all-fields
Storybook
