### ISSUE TITLE
Resource Editor Component: Media (MVP)

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/iiif-manifest-editor#94]
This is used as the **body** of a Media Annotation. It is also used for `thumbnail`, `logo`, and possibly `rendering`.
For properties that can be a media item or an array of media items, this is the widget to edit the item. It's also used to set the body of a media annotation (inline or modal)? in #96

### Source
| property | editable here | has further editor |
|-----------|----------------|---------------------|
| "id or source" | yes | no |

This is the first thing in the running order of the component. Like the New Canvas #52 , the user pastes in a URL.
When set, the #45 is invoked. This also validates that the URL is accessible - a file of the desktop won't work!

 - If it's an image, we can measure its w,h in the DOM. (If it's an image that doesn't work in a browser, it shouldn't be used for thumbs, logos etc).
 - If it's an image service (the root, or the info.json), we need to pick a sensible size based on `maxWidth` and/or the `sizes` array: this size becomes the w,h of the media item itself, and the image service gets added to the the image resource we create.
 - If the URL is a parameterisation of an image service, we set the image resource to this particular w,h and add the image service to the image resource

This analysis can set many of not all of the technical properties below automatically.
In a later phase this can invoke #95 to get technical data about AV.

In the wireframes it is _nearly_ this https://preview.uxpin.com/cabb8dec496a444a18e1ed442230485a02c17484#/pages/147630326/simulate/sitemap?mode=i
...but that needs to show a service.

In that image there is a large-ish thumbnail. If the resource is an image with an image service, the ME can pick a thumbnail from that. If not - it's an image with no image service - just use the full image, scaled down.

This is an example of a resource that _could_ have metadata, summary, requiredStatement etc, but is very unlikely to. So we may want to hide possible but rare properties in a separate section at the end.

### Technical Properties
_For Manifest these are simple strings or string arrays, from configured lists_
| property | editable here | has further editor |
|-----------|----------------|---------------------|
| type | `Image` or `Sound` or `Video` | no |
| format | (media type) | no |
| width | (free integer) | no |
| height | (free integer) | no |
| duration | (free float) | no |
| service | yes - just a single URL | no*  |

We don't need a separate image service editor component/widget (UI to set the various props of a IIIF Image Service), we only ever need a single URL and the analyser can go and get the details. The image service must always exist external to the editor.

### Simple Descriptive Properties
_(string values, or lists of strings, or maps, or lists of pairs of maps)_
| property | editable here | has further editor |
|-----------|----------------|---------------------|
| label | #67 | no |
| metadata | #68 | no |
| summary | #67 | no |
| requiredStatement | #67 | no |
| rights | #73 | no |

**Comment by tomcrane** [comment]
This component (or more probably its associated modal) is the integration point for hosting media (whatever that might be - DLCS, etc, doesn't matter).

Rather than having to supply an existing URL of media (or image service), you would create that here (e.g., by uploading a source image or video).

**Comment by stephenwf** [comment]
@tomcrane for the storybook, could we dodge the question of modal for now? Split into 2 storybook entries, one for the full form, one for the snippet?

**Comment by tomcrane** [comment]
Agreed - I'll go back and update after the first pass through.

In the HTML version I sometimes used "mini" and "full" - where full might be a modal or might be something else.

**Comment by tomcrane** [comment]
There are some advanced features of the **Resource Editor Component** that are particularly relevant when it is being used to provide the body of a `painting` annotation.

This is when the body is not just the resource, but some selection or transformation of the resource, as described in https://github.com/digirati-co-uk/iiif-manifest-editor/issues/31.

We need to allow for the body to be a crop of a resource, or a rotation, or an ImageApiSelector:

https://github.com/IIIF/cookbook-recipes/issues/40

The ImageApiSelector can govern any aspect of the Image Request:
https://iiif.io/api/annex/openannotation/#iiif-image-api-selector

This doesn't mean that viewers will understand what is happening, though.

I think it's too much of a push to get this into phase 1, but when designing the UI for providing this information, whether it's a modal or a right-hand editor, we need to allow for future:

 - [ ] Point at which the UI can extend to browsing a service like DLCS, including the ability to add a new resource to that remote service at this point
 - [ ] Extending the UI to advanced features; using annotation selectors and/or the ImageAPISeletor to qualify the resource.
